### ISSUE TITLE
test format

### ISSUE THREAD

**Issue by zoemccormick** [zoemccormick/Tutorial#4]
Here are the steps I took to run consul and greymatter in minikube:

1. `git clone https://github.com/hashicorp/consul-helm`
 - in values.yaml, comment out both sections beginning with `affinity: |`. This allows consul to run in minikube.  Enable the ui, enable the server, and enable the client.  In the client section - specify the configmaps (which will have the consul configurations for the services to be registered) in the form of 
```
extraVolumes:
-  type: configMap
      name: edge
      load: true
```
- in templates/server-service.yaml, add under `spec`, `type: ClusterIP` and comment out `clusterIP: None`

2. In deciphernow/helm-charts/control/values.yaml, add
```
    gm_control_cmd:
      type: 'value'
      value: 'consul'
    gm_control_consul_dc:
      type: 'value'
      value: 'dc1'
    gm_control_consul_hostport:
      type: 'value'
      value: 'consul-consul-server:8500'
```

3. Follow this guide: https://github.com/DecipherNow/helm-charts/blob/release-2.0/docs/Deploy%20with%20Minikube.md with the following injections:
- After minikube start and helm init, add the configMaps for the services: `kubectl create configmap edge --from-file=edge.json` (using edge as an example), and the json configuration should look like (anything within the service definition https://www.consul.io/docs/agent/services.html):
```
{
    "address": "edge",
    "name": "edge",
    "tags": ["tbn-cluster"],
    "port": 8080
  }
```

  - before installing greymatter in `helm install greymatter ... ` run `helm install ./consul-helm --name consul`.  Then install greymatter and control should be able to discover from consul.  This can be verified in both the control logs and the clusters if you run `kubectl port-forward gm-control-api-{whatever POD id is} 5555:5555` and then using the cli you can confirm the instances.
